# Generated by Django 5.0.14 on 2025-06-02 23:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('designation', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('co', 'CENTRAL OFFICE'), ('ncr', 'NATIONAL CAPITAL REGION'), ('car', 'CORDILLERA ADMINISTRATIVE REGION'), ('r1', 'Region 1'), ('r2', 'Region 2'), ('r3', 'Region 3'), ('r4a', 'CALABARZON'), ('r4b', 'MIMAROPA'), ('r5', 'Region 5'), ('r6', 'Region 6'), ('r7', 'Region 7'), ('r8', 'Region 8'), ('r9', 'Region 9'), ('r10', 'Region 10'), ('r11', 'Region 11'), ('r12', 'Region 12'), ('r13', 'Region 13'), ('barmm', 'BANGSAMORO AUTONOMOUS REGION IN MUSLIM MINDANAO')], max_length=10, null=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('ier_inv', 'IER Investigator'), ('pci_inv', 'PCI Investigator'), ('dir', 'Director'), ('sho', 'Summary Hearing Officer'), ('comr', 'Commissioner')], max_length=20, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='customuser_groups_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_permissions_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='iec_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.DateField()),
                ('iec_ref', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('complainant', models.CharField(max_length=100)),
                ('respondent', models.CharField(max_length=100)),
                ('charge', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('received', 'Initial Evaluation Report'), ('2', 'Completed')], default='received', max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_iec_records', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_iec_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
