# Generated by Django 5.0.14 on 2025-06-03 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcmisapp', '0002_remove_iec_records_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialEvaluationReport',
            fields=[
                ('iec_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='initial_evaluation_report_details', serialize=False, to='sdcmisapp.iec_records')),
                ('submitted_on', models.DateField(auto_now_add=True)),
                ('director_approval_date', models.DateField(blank=True, null=True, verbose_name='IER Approved by Director On')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Submission Remarks')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_iers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
