# Generated by Django 5.0.14 on 2025-06-03 08:00

import sdcmisapp.workflow_def
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcmisapp', '0003_initialevaluationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iec_records',
            name='status',
            field=models.CharField(choices=[('initial_evaluation', 'Initial Evaluation Report'), ('notice_pci', 'Notice of Pre-Charge Investigation'), ('comment_counter_affidavit', 'Comment/Counter Affidavit'), ('pci_report_draft_charge', 'PCI Report and/or Draft Formal Charge'), ('formal_charge', 'Formal Charge'), ('assign_hearing_officer', 'Assignment of Hearing Officer'), ('summons', 'Summons'), ('answer', 'Answer'), ('pre_hearing_conference', 'Pre-Hearing Conference'), ('position_paper', 'Position Paper'), ('clarificatory_hearing', 'Clarificatory Hearing'), ('report_investigation_draft_decision', 'Report of Investigation and Draft Decision/Resolution'), ('deliberations', 'Deliberations'), ('resolved', 'Resolved')], default=sdcmisapp.workflow_def.get_initial_status_key, max_length=100),
        ),
    ]
