# Generated by Django 5.0.14 on 2025-06-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcmisapp', '0004_alter_iec_records_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ier_inv', 'Initial Evaluator'), ('pci_inv', 'PCI Investigator'), ('dir', 'Director'), ('sho', 'Summary Hearing Officer'), ('comr', 'Commissioner')], max_length=20, null=True),
        ),
    ]
