# Generated by Django 5.0.14 on 2025-06-03 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcmisapp', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreChargeInvestigation',
            fields=[
                ('iec_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pre_charge_investigation_details', serialize=False, to='sdcmisapp.iec_records')),
                ('notice_pci_submitted_on', models.DateField(blank=True, null=True, verbose_name='Notice of PCI Submitted On (by staff)')),
                ('notice_pci_respondent_received_on', models.DateField(blank=True, null=True, verbose_name='Notice of PCI Received by Respondent On')),
                ('notice_pci_remarks', models.TextField(blank=True, null=True, verbose_name='Notice of PCI Remarks')),
                ('comment_counter_affidavit_received_on', models.DateField(blank=True, null=True, verbose_name='Comment/Counter Affidavit Received On')),
                ('comment_counter_affidavit_remarks', models.TextField(blank=True, null=True, verbose_name='Comment/Counter Affidavit Remarks')),
                ('pci_report_submitted_on', models.DateField(blank=True, null=True, verbose_name='PCI Report/Draft Formal Charge Submitted On')),
                ('pci_report_remarks', models.TextField(blank=True, null=True, verbose_name='PCI Report/Draft Formal Charge Remarks')),
                ('notice_pci_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pci_notices', to=settings.AUTH_USER_MODEL, verbose_name='Notice of PCI Submitted By')),
                ('pci_report_submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_pci_reports', to=settings.AUTH_USER_MODEL, verbose_name='PCI Report/Draft Formal Charge Submitted By')),
            ],
        ),
    ]
