# Generated by Django 5.0.14 on 2025-06-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcmisapp', '0006_prechargeinvestigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='prechargeinvestigation',
            name='precharge_no',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Pre-Charge Investigation No.'),
        ),
    ]
